FROM docker.io/chimeralinux/chimera:latest AS src

ENV PIPX_GLOBAL_HOME=/usr/local

RUN apk add --no-cache python pipx && pipx install --global conan

FROM docker.io/chimeralinux/chimera:latest

COPY --from=src /usr/local /usr/local

RUN apk add --no-cache clang cmake libcxx libcxx-devel libcxxabi libcxxabi-devel libunwind libunwind-devel mold musl musl-devel ninja python
