FROM docker.io/debian:unstable

ARG CLANG_VERSION
ARG CMAKE_VERSION
ARG CONAN_VERSION

WORKDIR /opt

RUN apt update && apt install --no-install-recommends --yes wget xz-utils && \
    wget --no-check-certificate https://github.com/llvm/llvm-project/releases/download/llvmorg-${CLANG_VERSION}/LLVM-${CLANG_VERSION}-Linux-X64.tar.xz -O clang.tar.xz && \
    wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz -O cmake.tar.gz && \
    wget --no-check-certificate https://github.com/conan-io/conan/releases/download/${CONAN_VERSION}/conan-${CONAN_VERSION}-linux-x86_64.tgz -O conan.tar.gz
RUN tar tvf clang.tar.xz
RUN tar --directory /usr/local --strip-components 1 -xf clang.tar.xz && \
    tar --directory /usr/local --strip-components 1 -xf cmake.tar.gz && \
    tar --directory /usr/local -xf conan.tar.gz
